import requests
import xmltodict
import json

url = "https://openapi.gg.go.kr/GgHosptlM?KEY=337b4bebd30e4d419b85a1ba8c9c26a2&pSize=1000"
url2 = "https://openapi.gg.go.kr/GgHosptlM?KEY=337b4bebd30e4d419b85a1ba8c9c26a2&pIndex=2&pSize=1000"
content = requests.get(url).content
content2 = requests.get(url2).content

dict = xmltodict.parse(content)
dict2 = xmltodict.parse(content2)

jsonString = json.dumps(dict['GgHosptlM']['row'], ensure_ascii=False)   # <GgHosptlM> 태그의 <row> 정보
jsonString2 = json.dumps(dict2['GgHosptlM']['row'], ensure_ascii=False)

jsonObj = json.loads(jsonString)
jsonObj2 = json.loads(jsonString2)

# test_corpus = open('intent_2.txt', 'a',encoding= 'utf-8')
f =  open('total_train.txt', 'a',encoding= 'utf-8')
# f = open('intent_1.txt', 'r',encoding= 'utf-8')
# f2 = open('intent_2.txt', 'r',encoding= 'utf-8')
f3 = open('test.txt', 'a',encoding= 'utf-8')
count = 0
def remove_redundancy(list_A) :           # list 중복제거 함수
    set_list = set(list_A)
    remove_list = list(set_list)
    return remove_list


# 병원이름, 도시, 동, 종, 과목, 기타..
hos = []; city = []; s_c = []; treat = [];

for tag in jsonObj :
                hos.append(tag['BIZPLC_NM'])
                city.append(tag['SIGUN_NM'])
                split_s_c = str(tag['REFINE_LOTNO_ADDR']).split(' ')
                treat_split = str(tag['TREAT_SBJECT_CONT_INFO']).split(', ')
                for i in treat_split:
                    treat.append(i)
                if len(split_s_c) >= 3 :
                    s_c.append(split_s_c[2])
for tag in jsonObj2 :
                hos.append(tag['BIZPLC_NM'])
                city.append(tag['SIGUN_NM'])
                split_s_c = str(tag['REFINE_LOTNO_ADDR']).split(' ')
                treat_split = str(tag['TREAT_SBJECT_CONT_INFO']).split(', ')
                for i in treat_split:
                    treat.append(i)
                if len(split_s_c) >= 3:
                    s_c.append(split_s_c[2])

city = remove_redundancy(city); s_c = remove_redundancy(s_c)
treat = remove_redundancy(treat)
type = ['요양병원', '치과병원', '한방병원', '종합병원']

# for item in hos :
#     f.write(item + '\t' + 'NNG' + '\n')
for item in city :
    f.write(item + '\t' + 'NNG' + '\n')
# for item in s_c :
#     f.write(item + '\t' + 'NNG' + '\n')
# for item in treat :
#     f.write(item + '\t' + 'NNG' + '\n')
# for item in type :
#     f.write(item + '\t' + 'NNG' + '\n')
# f.close()
#
# for item in city :
#         for item2 in treat:
#                 f3.write('0000' + '\t' + item[:-1] + '에 있는 ' + item2 + ' 병원 리스트' +'\t\t' + '2' + '\n')
#                 f3.write('0000' + '\t' + item[:-1] + '에 있는 ' + item2 + ' 병원' + '\t\t' + '2' + '\n')
#                 f3.write('0000' + '\t' + item[:-1] + '에 있는 ' + item2 + ' 병원 목록' + '\t\t' + '2' + '\n')
# # Intent - 1
#
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 정보!' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 정보!' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 정보 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 정보 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전체정보 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전체정보 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 알려줘!' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '에 대해 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '에 대해 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '이 알고싶음' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '을 알고싶어' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '이 알고싶어요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '에 대해 알고싶습니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '에 대해 알고싶어요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '이 궁금해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '이 궁금해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '이 궁금하네요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 정보가 궁금해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 문의' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 문의할게요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 문의하고싶어요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '에 대해 문의하고 싶어요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 알려줄래?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 알려줄 수 있어?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 알려주실 수 있나요?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 선택' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 내용' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 내용 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 내용 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 내용 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 내용 궁금해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 내용 궁금하네요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 내용 궁금합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 내용에 대해 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 내용을 알고싶습니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 인포' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 인포 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 인포 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 인포 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 인포 궁금해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 인포 궁금하네요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 인포 궁금합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 인포를 알고싶습니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 관련 정보' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 관련 정보 알고싶어' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 관련 정보 말해줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 관련 모든 정보 알고 싶어' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 관련 모든 정보 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '과 관련된 정보 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '과 관련된 정보 궁금해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '과 관련된 정보 궁금합니다' + '\t\t' + '1' + '\n')
#
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목에 대해 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목 내용' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목!' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목에 대해 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목 내용' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목!' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목에 대해 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목 내용' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목에 대해 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목에 대해 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목에 대해 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목에 대해 궁금합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목에 대해 궁금합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목에 대해 궁금합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목에 대해 궁금하네요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목에 대해 궁금하네요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목에 대해 궁금하네요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목에 대한 정보' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목에 대한 정보' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목에 대한 정보' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목에 대해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목에 대해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목에 대해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목 정보' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목 정보' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목 정보' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목 정보 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목 정보 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목 정보 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목!' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목 알려줘!' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목을 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '에 대한 진료과목 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '애 대한 진료과목 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목이 알고싶어' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목이 알고싶어요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '의 진료과목이 알고싶습니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '에 대한 진료과목이 알고싶어요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목이 궁금해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목이 궁금해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목 문의' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목 문의할게요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목 알려줄래?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목 알려줄 수 있어?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목 알려주실 수 있나요?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '에 대한 진찰과목 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '에 대한 진찰과목 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목이 알고싶어' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목이 알고싶어요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '의 진찰과목이 알고싶습니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '에 대한 진찰과목 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목이 궁금해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목 문의' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목 알려줄래?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목 알려줄 수 있어?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목 알려주실 수 있나요?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '은 어떤걸 진찰하나요?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '은 어떤걸 진료하나요?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰내용' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료내용' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 과목' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 종목' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 종목 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 종목 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 종목 알려주셈' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 종목 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 종목 궁금해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 종목 궁금합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문 알려주셈' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문 궁금해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문 궁금해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문 궁금합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목 알려주셈' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목 궁금해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목 궁금해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목 궁금합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목을 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목 궁금하네요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목 알고싶어' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목이 궁금하군요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목 궁금해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목좀' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진료과목 궁금행' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목을 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목 궁금하네요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목 알고싶어' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목이 궁금하군요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목 궁금해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목좀' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 진찰과목 궁금행' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목을 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목 궁금하네요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목 알고싶어' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목이 궁금하군요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목 궁금해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목좀' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전문과목 궁금행' + '\t\t' + '1' + '\n')
#
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 주소!' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 주소 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 주소 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 주소 알려줘!' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 주소를 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 주소 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '에 대한 주소 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '에 대한 주소 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '의 주소가 알고싶음' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 주소가 알고싶어' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 주소가 알고싶어요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '의 주소에 대해 알고싶습니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 주소가 알고싶어요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 주소 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 주소 궁금해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 주소가 궁금해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 주소가 궁금하네요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 주소 문의' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 주소 문의할게요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 주소 문의하고싶어요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 주소 알려줄래?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 주소 알려줄 수 있어?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 주소 알려주실 수 있나요?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 위치!' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 위치 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 위치 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 위치 알려줘!' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 위치를 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 위치 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '에 대한 위치 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '에 대한 위치 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '의 위치가 알고싶음' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 위치가 알고싶어' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 위치가 알고싶어요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '의 위치에 대해 알고싶습니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 위치가 알고싶어요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 위치 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 위치 궁금해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 위치가 궁금해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 위치가 궁금하네요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 위치 문의' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 위치 문의할게요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 위치 문의하고싶어요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 위치 알려줄래?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 위치 알려줄 수 있어?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 위치 알려주실 수 있나요?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 가는 길' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 가는 길 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 가는 길 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 가는 길 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 가는 길 궁금해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 가는 길 궁금해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 가는 길 궁금합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 가는 길 문의' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 가는 길 문의해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 가는 길 문의합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 가는 길 부탁' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 가는 길 부탁해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 가는 길 부탁합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 가는 길 요청' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 가는 길 요청해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 가는 길 요청합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 찾아가기' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 찾아가기 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 찾아가기 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 찾아가기 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 찾아가기 궁금해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 찾아가기 궁금해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 찾아가기 궁금합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 찾아가기 문의' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 찾아가기 문의해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 찾아가기 문의합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 찾아가기 부탁' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 찾아가기 부탁해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 찾아가기 부탁합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 찾아가기 요청' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 찾아가기 요청해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 찾아가기 요청합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 길찾기' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 길찾기 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 길찾기 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 길찾기 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 길찾기 궁금해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 길찾기 궁금해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 길찾기 궁금합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 길찾기 문의' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 길찾기 문의해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 길찾기 문의합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 길찾기 부탁' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 길찾기 부탁해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 길찾기 부탁합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 길찾기 요청' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 길찾기 요청해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 길찾기 요청합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 네비게이션' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 네비게이션 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 네비게이션 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 네비게이션 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 네비게이션 궁금해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 네비게이션 궁금해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 네비게이션 궁금합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 네비게이션기 문의' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 네비게이션 문의해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 네비게이션 문의합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 네비게이션 부탁' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 네비게이션 부탁해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 네비게이션 부탁합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 네비게이션 요청' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 네비게이션 요청해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 네비게이션 요청합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 지도' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 지도 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 지도 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 지도 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 지도 궁금해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 지도 궁금해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 지도 궁금합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 지도 문의' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 지도 문의해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 지도 문의합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 지도 부탁' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 지도 부탁해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 지도 부탁합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 지도 요청' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 지도 요청해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 지도 요청합니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 어디야?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 어디있어?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 어디에 있어?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 어딨어?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 어디 위치해있어?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 어떻게 가?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 어딘지 찾아봐줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 어딘지 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 어딘지 알려주세요' + '\t\t' + '1' + '\n')
#
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전화번호!' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전화번호 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전화번호 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '에 대한 전화번호 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '에 대한 전화번호 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전화번호 알고싶음' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전화번호' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전화번호 알고싶어' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전화번호가 알고싶어요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전화번호가 알고싶습니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전화번호 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전화번호가 궁금해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전화번호가 궁금해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전화번호가 궁금하네요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전화번호 문의' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전화번호 문의할게요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전화번호 알려줄래?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전화번호 알려줄 수 있어?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 전화번호 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 번호!' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 번호 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 번호 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '에 대한 번호 알려줘' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + '에 대한 번호 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 번호 알고싶음' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 번호' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 번호 알고싶어' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 번호가 알고싶어요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 번호가 알고싶습니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 번호 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 번호가 궁금해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 번호가 궁금해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 번호가 궁금하네요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 번호 문의' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 번호 문의할게요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 번호 알려줄래?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 번호 알려줄 수 있어?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 번호 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락처 알고싶어' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락처가 알고싶어요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락처가 알고싶습니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락처 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락처가 궁금해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락처가 궁금해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락처가 궁금하네요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락처 문의' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락처 문의할게요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락처 알려줄래?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락처 알려줄 수 있어?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락처 알려주세요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락방법' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락방법 알고싶어' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락방법 알고싶어요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락방법 알고싶습니다' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락방법 궁금' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락방법 궁금해' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락방법 궁금해요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락방법 궁금하네요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락방법 문의' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락방법 문의할게요' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락방법 알려줄래?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락방법 알려줄 수 있어?' + '\t\t' + '1' + '\n')
#         test_corpus.write('0000' + '\t' + tag['BIZPLC_NM'] + ' 연락방법 알려주세요' + '\t\t' + '1' + '\n')
# test_corpus.close()
# f.close()
# f2.close()


# Intent 2-1
# sigun = []
# for item in jsonObj :
#     if item['BSN_STATE_NM'] == '영업중' :
#        sigun.append(item['SIGUN_NM'])
# sigun = remove_redundancy(sigun)

# for i in sigun :
#     # print('0000' + '\t' + i + ' 병원목록' + '\t\t' + '2' + '\n')
#     f.write('0000' + '\t' + i + ' 근처 병원 목록' + '\t\t' + '2' + '\n')


# Intent 2-2
# adress = []
# union = []
# new_union = []
# for tag in jsonObj :
#     if tag['BSN_STATE_NM'] == '영업중' :
#         add = str(tag['REFINE_LOTNO_ADDR']).split(' ')
#         if len(add) >= 3 :
#             adress.append(add[1:3])
#
# for tag2 in jsonObj2 :
#     if tag2['BSN_STATE_NM'] == '영업중' :
#         add2 = str(tag2['REFINE_LOTNO_ADDR']).split(' ')
#         if len(add2) >= 3 :
#             adress.append(add2[1:3])
#
# for i in adress :
#         if i not in union :
#             union.append(i)
# for i in union :
#     new_union.append(i[0] + ' ' + i[1])
#
#
# for i in new_union :
#     print('0000' + '\t' + i + ' 병원 목록' + '\t\t' + '2' + '\n')

# for i in new_union :
#     print('0000' + '\t' + i + ' 병원 목록' + '\t\t' + '2' + '\n')
    # f.write('0000' + '\t' + i + ' 주변 병원 전체' + '\t\t' + '2' + '\n')


#   Intent 2-3
# sigun = []; subject = []
# for item in jsonObj :
#     if item['BSN_STATE_NM'] == '영업중' :
#        sigun.append(item['SIGUN_NM'])
#                 '\t\t' + '2' + '\n')    # i = 시 j = 병원 (종)
#        subject.append(str(item['MEDINST_ASORTMT_NM'])[0:4])
# sigun = remove_redundancy(sigun); subject = remove_redundancy(subject)
#
# for i in sigun :
#     for j in subject :
#         print('0000' + '\t' + i + ' ' + j + ' 목록' +
#                 '\t\t' + '2' + '\n')    # i = 시 j = 병원 (종)

#         f.write('0000' + '\t' + i + ' ' + j + ' 목록' +


#   Intent 2-4
# sigun = []; treat = []
# for tag in jsonObj :
#     if tag['BSN_STATE_NM'] == '영업중' :
#         sigun.append(tag['SIGUN_NM'])
#
#         treat_split = str(tag['TREAT_SBJECT_CONT_INFO']).split(', ')
#         for i in treat_split :
#             treat.append(i)
#
# for tag2 in jsonObj2 :
#     if tag2['BSN_STATE_NM'] == '영업중':
#         treat_split2 = str(tag2['TREAT_SBJECT_CONT_INFO']).split(', ')
#         for i in treat_split2 :
#             treat.append(i)
# sigun = remove_redundancy(sigun); treat = remove_redundancy(treat)
#
# for i in sigun :
#     for j in treat :
#         print('0000' + '\t' + i + ' ' + j + ' 병원' +
#                 '\t\t' + '2' + '\n')    # i = 시 j = 병원 (진료과목)

#         f.write('0000' + '\t' + i + ' ' + j + ' 병원' +
#                 '\t\t' + '2' + '\n')    # i = 시 j = 병원 (진료과목)

# f.close